export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const ACTIVATE_TODO = 'ACTIVATE_TODO'
export const SET_ADD_EDIT_STATE = 'SET_ADD_EDIT_STATE'
export const INITDATA = 'INITDATA'
